# Generated by Django 5.1.1 on 2024-10-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spam',
            old_name='message',
            new_name='password',
        ),
    ]
